config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'

  resources :entries do
    resources :reviews
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  http_basic_authenticate_with name: 'andrey', password: 'secret96',
    except: [:index, :show]

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find params[:id]
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find params[:id]
  end

  def update
    @entry = Entry.find params[:id]

    if @entry.update entry_params
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def create
    @entry = Entry.new entry_params

    if @entry.save entry_params
      redirect_to @entry
    else
      render 'new'
    end
  end

  def destroy
    @entry = Entry.find params[:id]

    @entry.destroy
    redirect_to entries_path
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :subtitle, :text, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  http_basic_authenticate_with name: 'andrey', password: 'secret96',
    only: :destroy

  def create
    @entry = Entry.find params[:entry_id]
    @review = @entry.reviews.create review_params
    redirect_to entry_path @entry
  end

  def destroy
    @entry = Entry.find params[:entry_id]
    @review = @entry.reviews.find params[:id]
    @review.destroy

    redirect_to entry_path @entry
  end
  private
    def review_params
      params.require(:review).permit(:thoughts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/entries/_entry.html.erb
<div class="post-preview">
  <%= link_to entry_path entry do %>
    <h2 class="post-title">
      <%= entry.title %>
    </h2>
    <h3 class="post-subtitle">
      <%= entry.subtitle %>
    </h3>
  <% end %>
  <p class="post-meta">Posted by
    <a href="#"><%= entry.author %></a>
    on <%= entry.created_at.to_formatted_s :long_ordinal %></p>
</div>
<hr>

app/views/entries/_form.html.erb
<%= form_with model: @entry, local: true do |form| %>

  <% if @entry.errors.any? %>
  <div class="erros">
    <h2>
      <%= pluralize @entry.errors.count, 'error'%> prohibited this entry from being saved:
    </h2>
    <ul>
      <% @entry.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :subtitle %><br>
    <%= form.text_field :subtitle %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/entries/edit.html.erb
<%= link_to '< Back', entries_path %>

<h2>Edit Entry</h2>

<%= render 'form' %>

app/views/entries/index.html.erb
<% provide :title, 'Journal' %>
<% content_for :header do %>
Journal
<% end %>
<%= render @entries %>

<!-- Pager -->
<div class="clearfix">
  <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
</div>

app/views/entries/new.html.erb
<%= link_to '< Back', entries_path %>
<h1>New Entry</h1>

<%= render 'form' %>

app/views/entries/show.html.erb
<% provide :title, @entry.title %>

<% content_for :subheader do %>
  <%= @entry.subtitle %>
<% end %>

<%= link_to '< Back', entries_path %>

<h4><%= @entry.created_at.to_formatted_s :long_ordinal %></h4>
<p>
<%= @entry.text %>
</p>

<h2>Entry Reviews</h2>
<%= render @entry.reviews %>

<h2>Review your Entry:</h2>
<%= render 'reviews/form' %>

<div class="clearfix">
  <%= link_to 'Edit Entry', edit_entry_path, class: 'btn btn-primary float-left'%>
  <%= link_to 'Delete Entry', entry_path(@entry),
              method: :delete,
              data: { confirm: 'Are you sure you want to get rid of this entry?' },
              class: 'btn btn-primary float-right' %>
</div>

app/views/home/index.html.erb
<% provide :title, "Home" %>

<h1>Great New Day!</h1>
<%= link_to 'Journal', controller: 'entries' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | Self Learning Experiment</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <%= render 'shared/pageheader' %>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <%= yield %>
        </div>
      </div>
    </div>

    <hr />
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: [@entry, @entry.reviews.build], local: true do |form| %>
  <p>
    <%= form.label :thoughts %>
    <br  />
    <%= form.text_area :thoughts %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<p>
  <strong><%= review.created_at.to_formatted_s :long_ordinal %></strong>
  <%= review.thoughts %>
</p>
<p>
  <%= link_to 'Destroy Review', [review.entry, review],
              method: :delete,
              data: { confirm: 'Ready to delete this review?' }%>
</p>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Andrey Esaulov 2018</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'New Entry', new_entry_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pageheader.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1><%= yield :title %></h1>
          <span class="subheading"><%= yield :subheader %></span>
        </div>
      </div>
    </div>
  </div>
</header>